### ISSUE TITLE
problem install subliminal synology

### ISSUE THREAD

**Issue by smika** [Mar2zz/LaSi#28] opened 2012-03-03 12:59 UTC
# https://github.com/Diaoul/subliminal

_###############################################################_

Options:
1. Install Subliminal
2. Back to menu
Q. Quit
Choose an option: 1

Are you sure you want to continue and install Subliminal?

Package textutils (2.1-5) installed in root is up to date.
Nothing to be done
Successfully terminated.
/opt/local/lib/python2.5/site-packages (in --site-dirs) does not exist
Searching for pip
Best match: pip 1.1
Processing pip-1.1-py2.6.egg
pip 1.1 is already the active version in easy-install.pth
Installing pip script to /opt/local/bin
Installing pip-2.6 script to /opt/local/bin

Using /opt/local/lib/python2.6/site-packages/pip-1.1-py2.6.egg
Processing dependencies for pip
Finished processing dependencies for pip
Downloading/unpacking subliminal
  Running setup.py egg_info for package subliminal
    file subliminal.py (for module subliminal) not found
Downloading/unpacking BeautifulSoup>=3.2.0 (from subliminal)
  Running setup.py egg_info for package BeautifulSoup
Downloading/unpacking guessit>=0.2 (from subliminal)
  Running setup.py egg_info for package guessit
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/root/build/guessit/setup.py", line 26, in <module>
        README = open(os.path.join(here, 'README.rst')).read()
    IOError: [Errno 2] No such file or directory: '/root/build/guessit/README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/root/build/guessit/setup.py", line 26, in <module>

```
README = open(os.path.join(here, 'README.rst')).read()
```

IOError: [Errno 2] No such file or directory: '/root/build/guessit/README.rst'

---

Command python setup.py egg_info failed with error code 1 in /root/build/guessit
Storing complete log in /root/.pip/pip.log

Failed! Installing Subliminal didn't finish, try again or:
Copy the text above and report an issue at the following address:
https://github.com/Mar2zz/LaSi/issues

**Comment by Jeroenve** [comment] 2012-03-03 13:03
That is an issue caused by guessit. See also https://github.com/Diaoul/subliminal/issues/62

**Comment by smika** [comment] 2012-03-04 15:32
Thanks... this solved the installation issue. At this moment I have the following error:

/opt/local/bin/subliminal -l nl --cache-dir=/volume1/@appstore/.cache/subliminal/ /volume1/downloads/dst/tv

This gives me the error:

Traceback (most recent call last):
  File "/opt/local/bin/subliminal", line 81, in <module>
    main()
  File "/opt/local/bin/subliminal", line 65, in main
    subtitles = subli.downloadSubtitles([unicode(x) for x in args.paths])
  File "/opt/local/lib/python2.6/site-packages/subliminal/subliminal.py", line 179, in downloadSubtitles
    subtitles = self.listSubtitles(entries, False)
  File "/opt/local/lib/python2.6/site-packages/subliminal/subliminal.py", line 142, in listSubtitles
    scan_result.extend(scan(e))
  File "/opt/local/lib/python2.6/site-packages/subliminal/subliminal.py", line 323, in scan
    result.extend(scan(os.path.join(entry, e), depth + 1))
  File "/opt/local/lib/python2.6/site-packages/subliminal/subliminal.py", line 323, in scan
    result.extend(scan(os.path.join(entry, e), depth + 1))
  File "/opt/local/lib/python2.6/site-packages/subliminal/subliminal.py", line 323, in scan
    result.extend(scan(os.path.join(entry, e), depth + 1))
  File "/opt/lib/python2.6/posixpath.py", line 70, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 24: ordinal not in range(128)

**Comment by Mar2zz** [comment] 2012-05-30 18:38
that's a subliminal issue you should post it at diaouls page. I think it has to do with syno's default charset and the one subliminal is using.

**Comment by Mar2zz** [comment] 2012-07-17 18:14
subliminal issue, so closing it.

**Closed as completed by Mar2zz** 2012-07-17 18:14 UTC
